### ISSUE TITLE
 pngquant-bin@5.0.2 postinstall

### ISSUE THREAD

**Issue by wangquansh** [imagemin/pngquant-bin#104]
node -v
11.10.0
npm -v
6.7.0

> mozjpeg@6.0.1 postinstall /Users/workspace-dt-automation/dt-web/node_modules/mozjpeg
> node lib/install.js

  ⚠ getaddrinfo ENOTFOUND raw.githubusercontent.com raw.githubusercontent.com:443
  ⚠ mozjpeg pre-build test failed
  ℹ compiling from source
  ✖ RequestError: read ECONNRESET
    at ClientRequest.req.once.err (/Users/workspace-dt-automation/dt-web/node_modules/got/index.js:111:21)
    at Object.onceWrapper (events.js:285:13)
    at ClientRequest.emit (events.js:197:13)
    at TLSSocket.socketErrorListener (_http_client.js:397:9)
    at TLSSocket.emit (events.js:197:13)
    at emitErrorNT (internal/streams/destroy.js:82:8)
    at emitErrorAndCloseNT (internal/streams/destroy.js:50:3)
    at processTicksAndRejections (internal/process/next_tick.js:76:17)

> pngquant-bin@5.0.2 postinstall /Users/workspace-dt-automation/dt-web/node_modules/pngquant-bin
> node lib/install.js

  ⚠ read ECONNRESET
  ⚠ pngquant pre-build test failed
  ℹ compiling from source
  ✖ Error: pngquant failed to build, make sure that libpng is installed
    at Promise.all.then.arr (/Users/workspace-dt-automation/dt-web/node_modules/bin-build/node_modules/execa/index.js:231:11)
    at processTicksAndRejections (internal/process/next_tick.js:81:5)
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! pngquant-bin@5.0.2 postinstall: `node lib/install.js`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the pngquant-bin@5.0.2 postinstall script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

Why would it fail?

**Comment by MWalid** [comment]
Here I'm having the same on Centos 7

**Comment by chengyaogit** [comment]
the same problem

**Comment by creeptosis** [comment]
`yum -y install libpng-devel` works for me

**Comment by hichamfilty** [comment]
i trying to install gatsby and keep getting same ERR. WHEN I DO: gatsby new file-name

**Comment by 1000ch** [comment]
Please make sure that [the dependencies are installed](https://github.com/imagemin/pngquant-bin#updating-pre-compiled-binaries).

**Comment by leesren** [comment]
I use Mac and It work for me.

```bash
brew install libpng
npm  i 

```
