### ISSUE TITLE
"Unknown system error -86" when building on Apple Silicon

### ISSUE THREAD

**Issue by lhazell** [imagemin/pngquant-bin#121]
If this is a real issue, I have an Apple Silicon Mac and would like to help.

-----------------------------------------------------------------------
On Apple Silicon (arm64/arm64-apple-macos11) the build pre-test fails with the following issue:

```
0 verbose cli [
0 verbose cli   '/opt/homebrew/Cellar/node/15.11.0/bin/node',
0 verbose cli   '/opt/homebrew/bin/npm',
0 verbose cli   'install',
0 verbose cli   'pngquant-bin'
0 verbose cli ]
1 info using npm@7.6.2
2 info using node@v15.11.0
3 timing config:load:defaults Completed in 1ms
4 timing config:load:file:/opt/homebrew/lib/node_modules/npm/npmrc Completed in 0ms
5 timing config:load:builtin Completed in 0ms
6 timing config:load:cli Completed in 1ms
7 timing config:load:env Completed in 0ms
8 timing config:load:file:/Users/[...]/.npmrc Completed in 0ms
9 timing config:load:project Completed in 1ms
10 timing config:load:file:/Users/[...]/.npmrc Completed in 0ms
11 timing config:load:user Completed in 0ms
12 timing config:load:file:/opt/homebrew/etc/npmrc Completed in 0ms
13 timing config:load:global Completed in 0ms
14 timing config:load:cafile Completed in 0ms
15 timing config:load:validate Completed in 0ms
16 timing config:load:setUserAgent Completed in 0ms
17 timing config:load:setEnvs Completed in 1ms
18 timing config:load Completed in 4ms
19 verbose npm-session f5bcdea3e3ec24c2
20 timing npm:load Completed in 11ms
21 timing arborist:ctor Completed in 0ms
22 timing idealTree:init Completed in 309ms
23 timing idealTree:userRequests Completed in 2ms
24 silly idealTree buildDeps
25 silly fetch manifest pngquant-bin@*
26 verbose shrinkwrap failed to load node_modules/.package-lock.json out of date, updated: node_modules
27 http fetch GET 304 https://registry.npmjs.org/pngquant-bin 404ms (from cache)
28 silly placeDep ROOT pngquant-bin@6.0.0 OK for: bootstrap-gulp-starter@1.0.0 want: *
29 silly fetch manifest execa@^4.0.0
30 http fetch GET 304 https://registry.npmjs.org/execa 63ms (from cache)
31 timing idealTree:#root Completed in 473ms
32 silly placeDep node_modules/pngquant-bin execa@4.1.0 OK for: pngquant-bin@6.0.0 want: ^4.0.0
33 silly fetch manifest cross-spawn@^7.0.0
34 silly fetch manifest get-stream@^5.0.0
35 silly fetch manifest is-stream@^2.0.0
36 silly fetch manifest merge-stream@^2.0.0
37 silly fetch manifest npm-run-path@^4.0.0
38 silly fetch manifest onetime@^5.1.0
39 http fetch GET 304 https://registry.npmjs.org/get-stream 58ms (from cache)
40 http fetch GET 304 https://registry.npmjs.org/onetime 259ms (from cache)
41 http fetch GET 304 https://registry.npmjs.org/is-stream 323ms (from cache)
42 http fetch GET 304 https://registry.npmjs.org/merge-stream 326ms (from cache)
43 http fetch GET 304 https://registry.npmjs.org/cross-spawn 328ms (from cache)
44 http fetch GET 304 https://registry.npmjs.org/npm-run-path 328ms (from cache)
45 timing idealTree:node_modules/pngquant-bin Completed in 331ms
46 silly placeDep node_modules/pngquant-bin cross-spawn@7.0.3 OK for: execa@4.1.0 want: ^7.0.0
47 silly placeDep node_modules/pngquant-bin get-stream@5.2.0 OK for: execa@4.1.0 want: ^5.0.0
48 silly placeDep node_modules/pngquant-bin is-stream@2.0.0 OK for: execa@4.1.0 want: ^2.0.0
49 silly placeDep node_modules/pngquant-bin merge-stream@2.0.0 OK for: execa@4.1.0 want: ^2.0.0
50 silly placeDep node_modules/pngquant-bin npm-run-path@4.0.1 OK for: execa@4.1.0 want: ^4.0.0
51 silly placeDep node_modules/pngquant-bin onetime@5.1.2 OK for: execa@4.1.0 want: ^5.1.0
52 silly fetch manifest path-key@^3.1.0
53 silly fetch manifest shebang-command@^2.0.0
54 silly fetch manifest which@^2.0.1
55 silly fetch manifest pump@^3.0.0
56 silly fetch manifest path-key@^3.0.0
57 http fetch GET 304 https://registry.npmjs.org/shebang-command 72ms (from cache)
58 http fetch GET 304 https://registry.npmjs.org/path-key 73ms (from cache)
59 http fetch GET 304 https://registry.npmjs.org/pump 72ms (from cache)
60 http fetch GET 304 https://registry.npmjs.org/which 78ms (from cache)
61 timing idealTree:node_modules/pngquant-bin/node_modules/execa Completed in 85ms
62 silly placeDep node_modules/pngquant-bin path-key@3.1.1 OK for: cross-spawn@7.0.3 want: ^3.1.0
63 silly placeDep node_modules/pngquant-bin shebang-command@2.0.0 OK for: cross-spawn@7.0.3 want: ^2.0.0
64 silly placeDep node_modules/pngquant-bin which@2.0.2 OK for: cross-spawn@7.0.3 want: ^2.0.1
65 silly fetch manifest shebang-regex@^3.0.0
66 http fetch GET 304 https://registry.npmjs.org/shebang-regex 68ms (from cache)
67 timing idealTree:node_modules/pngquant-bin/node_modules/cross-spawn Completed in 70ms
68 silly placeDep node_modules/pngquant-bin pump@3.0.0 OK for: get-stream@5.2.0 want: ^3.0.0
69 timing idealTree:node_modules/pngquant-bin/node_modules/get-stream Completed in 1ms
70 timing idealTree:node_modules/pngquant-bin/node_modules/is-stream Completed in 0ms
71 timing idealTree:node_modules/pngquant-bin/node_modules/merge-stream Completed in 0ms
72 timing idealTree:node_modules/pngquant-bin/node_modules/npm-run-path Completed in 0ms
73 timing idealTree:node_modules/pngquant-bin/node_modules/onetime Completed in 0ms
74 timing idealTree:node_modules/pngquant-bin/node_modules/path-key Completed in 0ms
75 timing idealTree:node_modules/pngquant-bin/node_modules/pump Completed in 0ms
76 silly placeDep node_modules/pngquant-bin shebang-regex@3.0.0 OK for: shebang-command@2.0.0 want: ^3.0.0
77 timing idealTree:node_modules/pngquant-bin/node_modules/shebang-command Completed in 2ms
78 timing idealTree:node_modules/pngquant-bin/node_modules/shebang-regex Completed in 0ms
79 timing idealTree:node_modules/pngquant-bin/node_modules/which Completed in 0ms
80 timing idealTree:buildDeps Completed in 963ms
81 timing idealTree:fixDepFlags Completed in 6ms
82 timing idealTree Completed in 1290ms
83 timing reify:loadTrees Completed in 1291ms
84 timing reify:diffTrees Completed in 17ms
85 silly reify moves {}
86 timing reify:retireShallow Completed in 0ms
87 timing reify:createSparse Completed in 1ms
88 timing reify:loadBundles Completed in 0ms
89 timing reifyNode:node_modules/pngquant-bin/node_modules/shebang-command Completed in 28ms
90 timing reifyNode:node_modules/pngquant-bin/node_modules/merge-stream Completed in 27ms
91 timing reifyNode:node_modules/imagemin-optipng Completed in 28ms
92 timing reifyNode:node_modules/pngquant-bin/node_modules/shebang-regex Completed in 29ms
93 timing reifyNode:node_modules/pngquant-bin/node_modules/onetime Completed in 29ms
94 timing reifyNode:node_modules/pngquant-bin/node_modules/npm-run-path Completed in 28ms
95 timing reifyNode:node_modules/pngquant-bin/node_modules/is-stream Completed in 28ms
96 timing reifyNode:node_modules/pngquant-bin/node_modules/path-key Completed in 29ms
97 timing reifyNode:node_modules/pngquant-bin/node_modules/which Completed in 29ms
98 timing reifyNode:node_modules/pngquant-bin/node_modules/pump Completed in 29ms
99 timing reifyNode:node_modules/pngquant-bin/node_modules/get-stream Completed in 28ms
100 timing reifyNode:node_modules/pngquant-bin/node_modules/cross-spawn Completed in 29ms
101 timing reifyNode:node_modules/pngquant-bin/node_modules/execa Completed in 29ms
102 timing reifyNode:node_modules/pngquant-bin Completed in 30ms
103 timing reifyNode:node_modules/optipng-bin Completed in 32ms
104 timing reify:unpack Completed in 33ms
105 timing reify:unretire Completed in 0ms
106 timing build:queue Completed in 0ms
107 timing build:link:node_modules/optipng-bin Completed in 0ms
108 timing build:link:node_modules/pngquant-bin Completed in 0ms
109 timing build:link:node_modules/pngquant-bin/node_modules/which Completed in 0ms
110 timing build:link Completed in 0ms
111 info run optipng-bin@6.0.0 postinstall node_modules/optipng-bin node lib/install.js
112 info run pngquant-bin@6.0.0 postinstall node_modules/pngquant-bin node lib/install.js
113 http fetch POST 200 https://registry.npmjs.org/-/npm/v1/security/advisories/bulk 358ms
114 timing auditReport:getReport Completed in 360ms
115 timing metavuln:cache:get:security-advisory:marked:JjtyKgNaS05d2O5Se+mSj2PacQR5XJdOJBr/HXX1ZcwtaGUHc+6vChytTQM3xmL5a09+HewqHwMHONRUq1G2JQ== Completed in 15ms
116 timing metavuln:cache:get:security-advisory:clean-css:CieRffbE1nPyVol67lB6RtDImjfmW7zQ2s5sXvqm8/SQIVEQZKoBnBk0bcEvROmNVksCApCakQmyxPZs0AXNng== Completed in 16ms
117 timing metavuln:cache:get:security-advisory:axios:nGn3vXHBr1MXdEUoCk2XqIzU8gDyqMJzOSF3bSVg7fKRpGqH686g8X7gNVmfdoD30lET3rsU8E009x0pQQVfAg== Completed in 17ms
118 timing metavuln:cache:get:security-advisory:minimist:8MDgP3O3yM8t8dcQHSMUtmH4UKJrKhWmsmV44L4YChIzoahEo+G6j24b+4BPItZck5h5zQFPFD39kOC/789lfA== Completed in 15ms
119 timing metavuln:cache:get:security-advisory:braces:KNqjr1CE0QC68S3zOEsplFbBx/OoDhCB5eW9YqBWUKIt+akMhIivd+sGFIcKkRpAVktYb+ArnkYQx4siXgYJIg== Completed in 16ms
120 http fetch GET 304 https://registry.npmjs.org/axios 64ms (from cache)
121 timing metavuln:packument:axios Completed in 66ms
122 timing metavuln:load:security-advisory:axios:1594 Completed in 1ms
123 timing metavuln:calculate:security-advisory:axios:1594 Completed in 67ms
124 http fetch GET 304 https://registry.npmjs.org/braces 82ms (from cache)
125 timing metavuln:packument:braces Completed in 82ms
126 timing metavuln:load:security-advisory:braces:786 Completed in 1ms
127 timing metavuln:calculate:security-advisory:braces:786 Completed in 83ms
128 http fetch GET 304 https://registry.npmjs.org/marked 82ms (from cache)
129 timing metavuln:packument:marked Completed in 83ms
130 timing metavuln:load:security-advisory:marked:1623 Completed in 0ms
131 timing metavuln:calculate:security-advisory:marked:1623 Completed in 83ms
132 http fetch GET 304 https://registry.npmjs.org/clean-css 89ms (from cache)
133 timing metavuln:packument:clean-css Completed in 91ms
134 timing metavuln:load:security-advisory:clean-css:785 Completed in 1ms
135 timing metavuln:calculate:security-advisory:clean-css:785 Completed in 92ms
136 http fetch GET 304 https://registry.npmjs.org/minimist 93ms (from cache)
137 timing metavuln:packument:minimist Completed in 93ms
138 timing metavuln:load:security-advisory:minimist:1179 Completed in 1ms
139 timing metavuln:calculate:security-advisory:minimist:1179 Completed in 94ms
140 timing metavuln:cache:get:security-advisory:access-sniff:ckr08O9SCv3gnRGkfkNACPdP12wq56H6eddPp15oxwwaEZpHGZqQs3GYQrZBGDpR5+14dky3g2le2Vr9hRYfOA== Completed in 2ms
141 http fetch GET 304 https://registry.npmjs.org/access-sniff 63ms (from cache)
142 timing metavuln:packument:access-sniff Completed in 63ms
143 timing metavuln:load:security-advisory:access-sniff:nGn3vXHBr1MXdEUoCk2XqIzU8gDyqMJzOSF3bSVg7fKRpGqH686g8X7gNVmfdoD30lET3rsU8E009x0pQQVfAg== Completed in 1ms
144 timing metavuln:calculate:security-advisory:access-sniff:nGn3vXHBr1MXdEUoCk2XqIzU8gDyqMJzOSF3bSVg7fKRpGqH686g8X7gNVmfdoD30lET3rsU8E009x0pQQVfAg== Completed in 64ms
145 timing metavuln:cache:get:security-advisory:micromatch:6Hdv/9HSh6TBKC1CYoX9JqnyAi5q0f0pB+S19ia7Yf8EyYlIonIcYrhYYC32YnFFZoEyzbV98/lmmbf9qWq6jA== Completed in 2ms
146 http fetch GET 304 https://registry.npmjs.org/micromatch 66ms (from cache)
147 timing metavuln:packument:micromatch Completed in 66ms
148 timing metavuln:load:security-advisory:micromatch:KNqjr1CE0QC68S3zOEsplFbBx/OoDhCB5eW9YqBWUKIt+akMhIivd+sGFIcKkRpAVktYb+ArnkYQx4siXgYJIg== Completed in 0ms
149 timing metavuln:calculate:security-advisory:micromatch:KNqjr1CE0QC68S3zOEsplFbBx/OoDhCB5eW9YqBWUKIt+akMhIivd+sGFIcKkRpAVktYb+ArnkYQx4siXgYJIg== Completed in 67ms
150 timing metavuln:cache:get:security-advisory:gulp-cssmin:zpp9vwWjftjJcyOnbmEVF6q9ZhBNaAXmBoJwFb51nH90PG4wsxEpNTZ160beH36Pp+GGcsrcxYNu90QYVQ2g1A== Completed in 1ms
151 http fetch GET 304 https://registry.npmjs.org/gulp-cssmin 213ms (from cache)
152 timing metavuln:packument:gulp-cssmin Completed in 214ms
153 timing metavuln:load:security-advisory:gulp-cssmin:CieRffbE1nPyVol67lB6RtDImjfmW7zQ2s5sXvqm8/SQIVEQZKoBnBk0bcEvROmNVksCApCakQmyxPZs0AXNng== Completed in 0ms
154 timing metavuln:calculate:security-advisory:gulp-cssmin:CieRffbE1nPyVol67lB6RtDImjfmW7zQ2s5sXvqm8/SQIVEQZKoBnBk0bcEvROmNVksCApCakQmyxPZs0AXNng== Completed in 214ms
155 timing metavuln:cache:get:security-advisory:panini:jpmuyLwykZhmRjrpb0hOl3sis/eRonHtJQg1GEYmujvk4L/Br508pDMe+hdwzi9uT5b3Wj5lRkz72xAnj2S6wA== Completed in 5ms
156 http fetch GET 304 https://registry.npmjs.org/panini 66ms (from cache)
157 timing metavuln:packument:panini Completed in 66ms
158 timing metavuln:load:security-advisory:panini:JjtyKgNaS05d2O5Se+mSj2PacQR5XJdOJBr/HXX1ZcwtaGUHc+6vChytTQM3xmL5a09+HewqHwMHONRUq1G2JQ== Completed in 0ms
159 timing metavuln:calculate:security-advisory:panini:JjtyKgNaS05d2O5Se+mSj2PacQR5XJdOJBr/HXX1ZcwtaGUHc+6vChytTQM3xmL5a09+HewqHwMHONRUq1G2JQ== Completed in 66ms
160 timing metavuln:cache:get:security-advisory:gonzales-pe-sl:mRvnbV354L7Wg2VJ4/MznH8Tjzdm2Ip685pBru3UdjkSuAUNWrNd3nMoFMQAOWzKd6pNCMeKkNkoVGbOVDSGNA== Completed in 16ms
161 timing metavuln:cache:get:security-advisory:blocking-proxy:esfR0TLdsWb4wf/9LDLcjtkSUllycRtQTFo2mGXWmlscDFJfZmFY7iQobbSYjQxlrGP3jfyc6IQo7BTqULOnoQ== Completed in 15ms
162 timing metavuln:cache:get:security-advisory:csscomb:P6FHjBfa9ieh71aVyT+n7gktibDk6+5oc/BndPOeBxUZW8ccLf9q0Z0DAqL07WKPCI0yCqIM5LBk+i90DiN57g== Completed in 15ms
163 timing metavuln:cache:get:security-advisory:meow:77nL6GjRTgs6PsZG9tit194Ki9THziHyRIcjBSdroet8DrYHx5VMZREYspMrKEYQf7FYG0Oh5nw/4kAKIyk2eg== Completed in 14ms
164 timing metavuln:cache:get:security-advisory:gulp-util:kdVUBCpcnd5mKKx0BdoPIHqRdxVJR5/iEPe+l1v3nPmDXN4eDiye9gp2ro2prgaXhfdKx9ckLUpleh8VkF2zCw== Completed in 15ms
165 timing metavuln:cache:get:security-advisory:rc:5CaxaUsjK4hm5YGxZdsHBERbkhg2ayjB1F7KkltT/spva+03R7PxDydCg1iRXZrD/kq/c4RheFJZFfjh0Cjw0w== Completed in 14ms
166 timing metavuln:cache:get:security-advisory:webdriver-manager:HQCnPZRKdILckzoAQd3V1wbzPjI/Nfk7ytZNBwDDoZ+E0tGJxD9GGk/6Juss2R+0w15bnYsjFfa3hshtBnGxRA== Completed in 13ms
167 timing metavuln:cache:get:security-advisory:gonzales-pe:MjZa4Y9I8jNWuvHjGgs3apEbk6cW9A9nlY70cTi38pUB1D7VFPlP4PuGDSLsHlxgl+B8Byr2HaGCwaCuoilyxw== Completed in 16ms
168 http fetch GET 304 https://registry.npmjs.org/gonzales-pe-sl 71ms (from cache)
169 timing metavuln:packument:gonzales-pe-sl Completed in 71ms
170 timing metavuln:load:security-advisory:gonzales-pe-sl:8MDgP3O3yM8t8dcQHSMUtmH4UKJrKhWmsmV44L4YChIzoahEo+G6j24b+4BPItZck5h5zQFPFD39kOC/789lfA== Completed in 0ms
171 timing metavuln:calculate:security-advisory:gonzales-pe-sl:8MDgP3O3yM8t8dcQHSMUtmH4UKJrKhWmsmV44L4YChIzoahEo+G6j24b+4BPItZck5h5zQFPFD39kOC/789lfA== Completed in 71ms
172 http fetch GET 304 https://registry.npmjs.org/gulp-util 94ms (from cache)
173 timing metavuln:packument:gulp-util Completed in 94ms
174 timing metavuln:load:security-advisory:gulp-util:8MDgP3O3yM8t8dcQHSMUtmH4UKJrKhWmsmV44L4YChIzoahEo+G6j24b+4BPItZck5h5zQFPFD39kOC/789lfA== Completed in 0ms
175 timing metavuln:calculate:security-advisory:gulp-util:8MDgP3O3yM8t8dcQHSMUtmH4UKJrKhWmsmV44L4YChIzoahEo+G6j24b+4BPItZck5h5zQFPFD39kOC/789lfA== Completed in 95ms
176 http fetch GET 304 https://registry.npmjs.org/blocking-proxy 97ms (from cache)
177 timing metavuln:packument:blocking-proxy Completed in 97ms
178 timing metavuln:load:security-advisory:blocking-proxy:8MDgP3O3yM8t8dcQHSMUtmH4UKJrKhWmsmV44L4YChIzoahEo+G6j24b+4BPItZck5h5zQFPFD39kOC/789lfA== Completed in 0ms
179 timing metavuln:calculate:security-advisory:blocking-proxy:8MDgP3O3yM8t8dcQHSMUtmH4UKJrKhWmsmV44L4YChIzoahEo+G6j24b+4BPItZck5h5zQFPFD39kOC/789lfA== Completed in 97ms
180 http fetch GET 304 https://registry.npmjs.org/meow 97ms (from cache)
181 timing metavuln:packument:meow Completed in 97ms
182 timing metavuln:load:security-advisory:meow:8MDgP3O3yM8t8dcQHSMUtmH4UKJrKhWmsmV44L4YChIzoahEo+G6j24b+4BPItZck5h5zQFPFD39kOC/789lfA== Completed in 0ms
183 timing metavuln:calculate:security-advisory:meow:8MDgP3O3yM8t8dcQHSMUtmH4UKJrKhWmsmV44L4YChIzoahEo+G6j24b+4BPItZck5h5zQFPFD39kOC/789lfA== Completed in 97ms
184 http fetch GET 304 https://registry.npmjs.org/csscomb 99ms (from cache)
185 timing metavuln:packument:csscomb Completed in 99ms
186 timing metavuln:load:security-advisory:csscomb:8MDgP3O3yM8t8dcQHSMUtmH4UKJrKhWmsmV44L4YChIzoahEo+G6j24b+4BPItZck5h5zQFPFD39kOC/789lfA== Completed in 0ms
187 timing metavuln:calculate:security-advisory:csscomb:8MDgP3O3yM8t8dcQHSMUtmH4UKJrKhWmsmV44L4YChIzoahEo+G6j24b+4BPItZck5h5zQFPFD39kOC/789lfA== Completed in 99ms
188 http fetch GET 304 https://registry.npmjs.org/gonzales-pe 100ms (from cache)
189 timing metavuln:packument:gonzales-pe Completed in 101ms
190 timing metavuln:load:security-advisory:gonzales-pe:8MDgP3O3yM8t8dcQHSMUtmH4UKJrKhWmsmV44L4YChIzoahEo+G6j24b+4BPItZck5h5zQFPFD39kOC/789lfA== Completed in 0ms
191 timing metavuln:calculate:security-advisory:gonzales-pe:8MDgP3O3yM8t8dcQHSMUtmH4UKJrKhWmsmV44L4YChIzoahEo+G6j24b+4BPItZck5h5zQFPFD39kOC/789lfA== Completed in 101ms
192 http fetch GET 304 https://registry.npmjs.org/webdriver-manager 148ms (from cache)
193 timing metavuln:packument:webdriver-manager Completed in 149ms
194 timing metavuln:load:security-advisory:webdriver-manager:8MDgP3O3yM8t8dcQHSMUtmH4UKJrKhWmsmV44L4YChIzoahEo+G6j24b+4BPItZck5h5zQFPFD39kOC/789lfA== Completed in 0ms
195 timing metavuln:calculate:security-advisory:webdriver-manager:8MDgP3O3yM8t8dcQHSMUtmH4UKJrKhWmsmV44L4YChIzoahEo+G6j24b+4BPItZck5h5zQFPFD39kOC/789lfA== Completed in 149ms
196 http fetch GET 304 https://registry.npmjs.org/rc 173ms (from cache)
197 timing metavuln:packument:rc Completed in 173ms
198 timing metavuln:load:security-advisory:rc:8MDgP3O3yM8t8dcQHSMUtmH4UKJrKhWmsmV44L4YChIzoahEo+G6j24b+4BPItZck5h5zQFPFD39kOC/789lfA== Completed in 0ms
199 timing metavuln:calculate:security-advisory:rc:8MDgP3O3yM8t8dcQHSMUtmH4UKJrKhWmsmV44L4YChIzoahEo+G6j24b+4BPItZck5h5zQFPFD39kOC/789lfA== Completed in 173ms
200 timing metavuln:cache:get:security-advisory:gulp-accessibility:5MYC3Mc3DKOrPqu+CDR/mG1Qrq7QwrsrN2B6ReJNRDTV2bhKJEL44FNwnkbqXlAHhGA83WkK61sUDLVZjAxqKA== Completed in 1ms
201 http fetch GET 304 https://registry.npmjs.org/gulp-accessibility 132ms (from cache)
202 timing metavuln:packument:gulp-accessibility Completed in 132ms
203 timing metavuln:load:security-advisory:gulp-accessibility:ckr08O9SCv3gnRGkfkNACPdP12wq56H6eddPp15oxwwaEZpHGZqQs3GYQrZBGDpR5+14dky3g2le2Vr9hRYfOA== Completed in 0ms
204 timing metavuln:calculate:security-advisory:gulp-accessibility:ckr08O9SCv3gnRGkfkNACPdP12wq56H6eddPp15oxwwaEZpHGZqQs3GYQrZBGDpR5+14dky3g2le2Vr9hRYfOA== Completed in 132ms
205 timing metavuln:cache:get:security-advisory:glob-stream:QqOEvOzFpuuhKFFzrVVKcoJy3vhGcamDwQ/yih73rsPsIUL/wThNua2KqIsEiMz18R4G4ko3WaOr0Tj4JhWGaw== Completed in 3ms
206 http fetch GET 304 https://registry.npmjs.org/glob-stream 78ms (from cache)
207 timing metavuln:packument:glob-stream Completed in 79ms
208 timing metavuln:load:security-advisory:glob-stream:6Hdv/9HSh6TBKC1CYoX9JqnyAi5q0f0pB+S19ia7Yf8EyYlIonIcYrhYYC32YnFFZoEyzbV98/lmmbf9qWq6jA== Completed in 0ms
209 timing metavuln:calculate:security-advisory:glob-stream:6Hdv/9HSh6TBKC1CYoX9JqnyAi5q0f0pB+S19ia7Yf8EyYlIonIcYrhYYC32YnFFZoEyzbV98/lmmbf9qWq6jA== Completed in 79ms
210 timing metavuln:cache:get:security-advisory:sass-lint:DDAy08tuIYyRruMtKNwLYBuuKxtQBU/QclJqlDQhx8oDuJXRIJ4pRFkR4b+Dkuh0X7WSeDFPuiUJHO44lpu77w== Completed in 2ms
211 http fetch GET 304 https://registry.npmjs.org/sass-lint 64ms (from cache)
212 timing metavuln:packument:sass-lint Completed in 64ms
213 timing metavuln:load:security-advisory:sass-lint:mRvnbV354L7Wg2VJ4/MznH8Tjzdm2Ip685pBru3UdjkSuAUNWrNd3nMoFMQAOWzKd6pNCMeKkNkoVGbOVDSGNA== Completed in 0ms
214 timing metavuln:calculate:security-advisory:sass-lint:mRvnbV354L7Wg2VJ4/MznH8Tjzdm2Ip685pBru3UdjkSuAUNWrNd3nMoFMQAOWzKd6pNCMeKkNkoVGbOVDSGNA== Completed in 64ms
215 timing metavuln:cache:get:security-advisory:csscomb:hM3iqlHtzEtu9+SBnA2iFmq3enyNJojQ5xQTMoM4dRvqxRECdLJ51ikFYAdTNJO95TlDIfXoFsv9FiaDxMmV0A== Completed in 3ms
216 timing metavuln:load:security-advisory:csscomb:MjZa4Y9I8jNWuvHjGgs3apEbk6cW9A9nlY70cTi38pUB1D7VFPlP4PuGDSLsHlxgl+B8Byr2HaGCwaCuoilyxw== Completed in 1ms
217 timing metavuln:calculate:security-advisory:csscomb:MjZa4Y9I8jNWuvHjGgs3apEbk6cW9A9nlY70cTi38pUB1D7VFPlP4PuGDSLsHlxgl+B8Byr2HaGCwaCuoilyxw== Completed in 4ms
218 timing metavuln:cache:get:security-advisory:vinyl-fs:zdz5n9CaC2nd6L+CoM7FNmiDfUA63Xu6+5fk04xBd19Q9Eoi69wHvPRX9MQbT00MVEGzBkA5eo1zreaPtUJxrw== Completed in 1ms
219 http fetch GET 304 https://registry.npmjs.org/vinyl-fs 53ms (from cache)
220 timing metavuln:packument:vinyl-fs Completed in 53ms
221 timing metavuln:load:security-advisory:vinyl-fs:QqOEvOzFpuuhKFFzrVVKcoJy3vhGcamDwQ/yih73rsPsIUL/wThNua2KqIsEiMz18R4G4ko3WaOr0Tj4JhWGaw== Completed in 0ms
222 timing metavuln:calculate:security-advisory:vinyl-fs:QqOEvOzFpuuhKFFzrVVKcoJy3vhGcamDwQ/yih73rsPsIUL/wThNua2KqIsEiMz18R4G4ko3WaOr0Tj4JhWGaw== Completed in 53ms
223 timing metavuln:cache:get:security-advisory:gulp-sass-lint:YqZipIDki12CVk3y20cm7SOD6LTOQrs9C1uyqOdAmVbS92VZetkrVeg91z2rgYKjYClFdE9lppXcV2yefEmVaw== Completed in 1ms
224 http fetch GET 304 https://registry.npmjs.org/gulp-sass-lint 53ms (from cache)
225 timing metavuln:packument:gulp-sass-lint Completed in 53ms
226 timing metavuln:load:security-advisory:gulp-sass-lint:DDAy08tuIYyRruMtKNwLYBuuKxtQBU/QclJqlDQhx8oDuJXRIJ4pRFkR4b+Dkuh0X7WSeDFPuiUJHO44lpu77w== Completed in 0ms
227 timing metavuln:calculate:security-advisory:gulp-sass-lint:DDAy08tuIYyRruMtKNwLYBuuKxtQBU/QclJqlDQhx8oDuJXRIJ4pRFkR4b+Dkuh0X7WSeDFPuiUJHO44lpu77w== Completed in 53ms
228 timing metavuln:cache:get:security-advisory:gulp-gh-pages:IQCrdKW6rGkQjfbiFamZzhQ8CHYnPGw71Xi/VbU/qfoUg2CX9e4ZihkZ6SbSXzC20cGWX7aEMOFElQ1mxlGyBg== Completed in 3ms
229 http fetch GET 304 https://registry.npmjs.org/gulp-gh-pages 49ms (from cache)
230 timing metavuln:packument:gulp-gh-pages Completed in 49ms
231 timing metavuln:load:security-advisory:gulp-gh-pages:zdz5n9CaC2nd6L+CoM7FNmiDfUA63Xu6+5fk04xBd19Q9Eoi69wHvPRX9MQbT00MVEGzBkA5eo1zreaPtUJxrw== Completed in 0ms
232 timing metavuln:calculate:security-advisory:gulp-gh-pages:zdz5n9CaC2nd6L+CoM7FNmiDfUA63Xu6+5fk04xBd19Q9Eoi69wHvPRX9MQbT00MVEGzBkA5eo1zreaPtUJxrw== Completed in 49ms
233 timing auditReport:init Completed in 1133ms
234 timing reify:audit Completed in 1493ms
235 info run pngquant-bin@6.0.0 postinstall { code: 1, signal: null }
236 timing reify:rollback:createSparse Completed in 10ms
237 timing reify:rollback:retireShallow Completed in 0ms
238 timing command:install Completed in 2958ms
239 verbose stack Error: command failed
239 verbose stack     at ChildProcess.<anonymous> (/opt/homebrew/lib/node_modules/npm/node_modules/@npmcli/promise-spawn/index.js:64:27)
239 verbose stack     at ChildProcess.emit (node:events:378:20)
239 verbose stack     at maybeClose (node:internal/child_process:1067:16)
239 verbose stack     at Process.ChildProcess._handle.onexit (node:internal/child_process:301:5)
240 verbose pkgid pngquant-bin@6.0.0
241 verbose cwd /Users/[...]
242 verbose Darwin 20.3.0
243 verbose argv "/opt/homebrew/Cellar/node/15.11.0/bin/node" "/opt/homebrew/bin/npm" "install" "pngquant-bin"
244 verbose node v15.11.0
245 verbose npm  v7.6.2
246 error code 1
247 error path /Users/[...]/node_modules/pngquant-bin
248 error command failed
249 error command sh -c node lib/install.js
250 error ⚠ spawn Unknown system error -86
250 error   ⚠ pngquant pre-build test failed
250 error   ℹ compiling from source
250 error   ✖ Error: pngquant failed to build, make sure that libpng is installed
250 error     at /Users/[...]/node_modules/execa/index.js:231:11
250 error     at runMicrotasks (<anonymous>)
250 error     at processTicksAndRejections (node:internal/process/task_queues:94:5)
250 error     at async Promise.all (index 0)
251 verbose exit 1
```

**Comment by Yuliang-Lee** [comment]
same problem in apple M1

**Comment by imjasonmiller** [comment]
The following fixed it in my case on an Apple M1:

```shell
/usr/sbin/softwareupdate --install-rosetta
```
