### ISSUE TITLE
Unable to install on OSX

### ISSUE THREAD

**Issue by Anahkiasen** [imagemin/pngquant-bin#40]
Getting this weird error:

```
$ npm install pngquant-bin

> pngquant-bin@3.0.0 postinstall /Users/anahkiasen/Sites/madewithlove/weholi/node_modules/pngquant-bin
> node lib/install.js

  ⚠ Invalid non-string/buffer chunk
  ⚠ pngquant pre-build test failed
  ℹ compiling from source
/Users/anahkiasen/Sites/madewithlove/weholi/node_modules/onetime/index.js:15
				throw new Error(fnName + ' can only be called once.');
				^

Error: callback() can only be called once.
    at /Users/anahkiasen/Sites/madewithlove/weholi/node_modules/onetime/index.js:15:11
    at /Users/anahkiasen/Sites/madewithlove/weholi/node_modules/download/index.js:153:5
    at ConcatStream.<anonymous> (/Users/anahkiasen/Sites/madewithlove/weholi/node_modules/concat-stream/index.js:36:43)
    at emitNone (events.js:72:20)
    at ConcatStream.emit (events.js:166:7)
    at finishMaybe (/Users/anahkiasen/Sites/madewithlove/weholi/node_modules/readable-stream/lib/_stream_writable.js:502:14)
    at endWritable (/Users/anahkiasen/Sites/madewithlove/weholi/node_modules/readable-stream/lib/_stream_writable.js:512:3)
    at ConcatStream.Writable.end (/Users/anahkiasen/Sites/madewithlove/weholi/node_modules/readable-stream/lib/_stream_writable.js:477:5)
    at DuplexWrapper.onend (/Users/anahkiasen/Sites/madewithlove/weholi/node_modules/readable-stream/lib/_stream_readable.js:539:10)
    at DuplexWrapper.g (events.js:260:16)
```

```
$ node --version && npm --version
v4.2.1
3.3.9
$ which pngquant
/usr/local/bin/pngquant
```

**Comment by shinnn** [comment]
Fixed in https://github.com/kevva/decompress/commit/b37729eacd0b39ac803eef2a6ca5d53adafb4057.
