### ISSUE TITLE
install fails

### ISSUE THREAD

**Issue by slopesidecreative** [imagemin/pngquant-bin#41]
I'm able to install on my local Mac but not on Ubuntu server, both with Node 0.10.26 and NPM 1.4.3 --any suggestions please. I am running $sudo npm install and i have full permissions. 

 pngquant-bin@3.0.1 postinstall /opt/web/static-test/node_modules/imagemin-pngquant/node_modules/pngquant-bin

 node lib/install.js

module.js:340
    throw err;
          ^
Error: Cannot find module 'through2'
    at Function.Module._resolveFilename (module.js:338:15)
    at Function.Module._load (module.js:280:25)
    at Module.require (module.js:364:17)
    at require (module.js:380:17)
    at Object.<anonymous> (/opt/web/static-test/node_modules/gulp-sourcemaps/index.js:2:15)
    at Module._compile (module.js:456:26)
    at Object.Module._extensions..js (module.js:474:10)
    at Module.load (module.js:356:32)
    at Function.Module._load (module.js:312:12)
    at Module.require (module.js:364:17)
npm ERR! pngquant-bin@3.0.1 postinstall: `node lib/install.js`
npm ERR! Exit status 8
npm ERR! 
npm ERR! Failed at the pngquant-bin@3.0.1 postinstall script.
npm ERR! This is most likely a problem with the pngquant-bin package,
npm ERR! not with npm itself.

---- and the debug log

47159 info pngquant-bin@3.0.1 Failed to exec postinstall script
47160 info /opt/web/static-test/node_modules/imagemin-pngquant/node_modules/pngquant-bin unbuild
47161 info preuninstall pngquant-bin@3.0.1
47162 info uninstall pngquant-bin@3.0.1
47163 verbose false,/opt/web/static-test/node_modules,/opt/web/static-test/node_modules/imagemin-pngquant/node_mod$
47164 verbose /opt/web/static-test/node_modules/imagemin-pngquant/node_modules/.bin,[object Object] binRoot
47165 info postuninstall pngquant-bin@3.0.1
47166 verbose about to build /opt/web/static-test/node_modules/imagemin-pngquant
47167 info /opt/web/static-test/node_modules/imagemin-pngquant unbuild
47168 info preuninstall imagemin-pngquant@4.2.0
47169 info uninstall imagemin-pngquant@4.2.0
47170 verbose true,/opt/web/static-test/node_modules,/opt/web/static-test/node_modules unbuild imagemin-pngquant@4$
47171 info postuninstall imagemin-pngquant@4.2.0
47172 error pngquant-bin@3.0.1 postinstall: `node lib/install.js`
47172 error Exit status 8
47173 error Failed at the pngquant-bin@3.0.1 postinstall script.

**Comment by slopesidecreative** [comment]
I'm going thru and installing missing module after missing module...through2, graceful-fs, vinyl, convert-source-map, etc... trying to get it to run the post install script.

**Comment by slopesidecreative** [comment]
The initial fail caused by the .npm file (apparently) caused NPM to geek out and stop installing. Even when run again it would not install the other dependencies even after imgmin-pngquaint would pass. 

So, the fix:
$ sudo rm -rf ~/.npm
then delete the node_modules directory
then, run $sudo npm install
