### ISSUE TITLE
Tunneling socket could not be established

### ISSUE THREAD

**Issue by gabrieledarrigo** [imagemin/pngquant-bin#45]
Hi guys, any idea on why this happens?

```
> pngquant-bin@3.1.0 postinstall /jenkins/workspace/package-nemesis/assets/node_modules/pngquant-bin
> node lib/install.js

  ⚠ tunneling socket could not be established, cause=connect EINVAL 0.0.12.56:80 - Local (0.0.0.0:0)
  ⚠ pngquant pre-build test failed
  ℹ compiling from source
  ✖ RequestError: pngquant failed to build, make sure that libpng-dev is installed
    at ClientRequest.<anonymous> (/jenkins/workspace/package-nemesis/assets/node_modules/got/index.js:69:21)
    at ClientRequest.g (events.js:273:16)
    at emitOne (events.js:90:13)
    at ClientRequest.emit (events.js:182:7)
    at ClientRequest.onError (/jenkins/workspace/package-nemesis/assets/node_modules/tunnel-agent/index.js:178:21)
    at ClientRequest.g (events.js:273:16)
    at emitOne (events.js:90:13)
    at ClientRequest.emit (events.js:182:7)
    at Socket.socketErrorListener (_http_client.js:295:9)
    at emitOne (events.js:90:13)
```

**Comment by shinnn** [comment]
Disable your network proxy, or set `HTTPS_PROXY` environment variable.
