### ISSUE TITLE
throw new TypeError('Path must be a string. Received ' + inspect(path));

### ISSUE THREAD

**Issue by Ohar** [imagemin/pngquant-bin#47]
I remove my `C:\dev\anglemine\node_modules` folder (where `anglemine` is my project name), try to reinstall all modules with `npm install` and got an error.
Also there is no `npm-debug.log` to attach.
```

> pngquant-bin@0.1.7 postinstall C:\dev\anglemine\node_modules\pngquant-bin
> node index.js

path.js:7
    throw new TypeError('Path must be a string. Received ' + inspect(path));
    ^

TypeError: Path must be a string. Received { name: 'pngquant.exe',
  url: 'https://raw.github.com/sindresorhus/node-pngquant-bin/v0.1.7/vendor/win/pngquant.exe' }
    at assertPath (path.js:7:11)
    at Object.basename (path.js:801:5)
    at C:\dev\anglemine\node_modules\download\index.js:35:43
    at each (C:\dev\anglemine\node_modules\each-async\each-async.js:63:4)
    at module.exports (C:\dev\anglemine\node_modules\download\index.js:33:5)
    at BinWrapper._download (C:\dev\anglemine\node_modules\pngquant-bin\node_modules\bin-wrapper\index.js:283:14)
    at BinWrapper.check (C:\dev\anglemine\node_modules\pngquant-bin\node_modules\bin-wrapper\index.js:75:10)
    at C:\dev\anglemine\node_modules\pngquant-bin\index.js:27:5
    at FSReqWrap.cb [as oncomplete] (fs.js:251:19)
- optipng-bin node_modules\grunt-contrib-imagemin\node_modules\optipng-bin
- log-symbols node_modules\grunt-contrib-imagemin\node_modules\optipng-bin\node_modules\log-symbols
- chalk node_modules\grunt-contrib-imagemin\node_modules\optipng-bin\node_modules\log-symbols\node_modules\chalk
- strip-ansi node_modules\grunt-contrib-imagemin\node_modules\optipng-bin\node_modules\log-symbols\node_modules\chalk\node_modules\strip-ansi

```
```
npm ERR! Windows_NT 6.1.7601
npm ERR! argv "C:\\Program Files\\nodejs\\node.exe" "C:\\Program Files\\nodejs\\node_modules\\npm\\bin\\npm-cli.js" "i"
npm ERR! node v6.0.0
npm ERR! npm  v3.8.8
npm ERR! code ELIFECYCLE

npm ERR! pngquant-bin@0.1.7 postinstall: `node index.js`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the pngquant-bin@0.1.7 postinstall script 'node index.js'.
npm ERR! Make sure you have the latest version of node.js and npm installed.
npm ERR! If you do, this is most likely a problem with the pngquant-bin package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     node index.js
npm ERR! You can get information on how to open an issue for this project with:
npm ERR!     npm bugs pngquant-bin
npm ERR! Or if that isn't available, you can get their info via:
npm ERR!     npm owner ls pngquant-bin
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     C:\dev\anglemine\npm-debug.log
```

**Comment by shinnn** [comment]
> pngquant-bin@0.1.7

Too older version.
