### ISSUE TITLE
Error building on windows

### ISSUE THREAD

**Issue by tarungarg546** [imagemin/pngquant-bin#48]
Hey, 
My platform
- NPM 3.10.3
- Node 6.3.0
- OS Windows 7 64 bit.

I am getting below error when i am trying to install this binary.

```sh
$ npm i pngquant-bin -S
(node:1580) fs: re-evaluating native module sources is not supported. If you are using the graceful-fs module, please update it to a more recent version.

> pngquant-bin@3.1.1 postinstall C:\image-minifier-sqd\node_modules\pngquant-bin
> node lib/install.js

  ‼ The `C:\image-minifier-sqd\node_modules\pngquant-bin\vendor\pngquant.exe` binary doesn't seem to work correctly
  ‼ pngquant pre-build test failed
  i compiling from source
  × Error: pngquant failed to build, make sure that libpng-dev is installed
    at ChildProcess.exithandler (child_process.js:202:12)
    at emitTwo (events.js:106:13)
    at ChildProcess.emit (events.js:191:7)
    at maybeClose (internal/child_process.js:852:16)
    at Socket.<anonymous> (internal/child_process.js:323:11)
    at emitOne (events.js:96:13)
    at Socket.emit (events.js:188:7)
    at Pipe._handle.close [as _onclose] (net.js:492:12)
image-minifier-sqd@1.0.0 C:\image-minifier-sqd
`-- pngquant-bin@3.1.1
```

**Comment by shinnn** [comment]
The error message clearly tells you what you should do.
