### ISSUE TITLE
Complains about libpng-dev dependency in Windows 8.1

### ISSUE THREAD

**Issue by KennyLindahl** [imagemin/pngquant-bin#51]
I get this when trying to install on Windows 8.1, is it a known issue or could it be resolved?
It works on Mac, Windows 10 and Linux.

```
> pngquant-bin@3.1.1 postinstall C:\Users\my-user\Projects\my-project\node_modules\pngquant-bin
> node lib/install.js

  ‼ unable to get local issuer certificate
  ‼ pngquant pre-build test failed
  i compiling from source
  × Error: pngquant failed to build, make sure that libpng-dev is installed
    at ChildProcess.exithandler (child_process.js:202:12)
    at emitTwo (events.js:100:13)
    at ChildProcess.emit (events.js:185:7)
    at maybeClose (internal/child_process.js:850:16)
    at Process.ChildProcess._handle.onexit (internal/child_process.js:215:5)
```

Thanks in advance.

**Comment by kevva** [comment]
https://github.com/imagemin/pngquant-bin/search?utf8=%E2%9C%93&q=libpng-dev&type=Issues
