### ISSUE TITLE
alpine-node:4, npm install > Error: not implemented

### ISSUE THREAD

**Issue by airtonix** [imagemin/pngquant-bin#56]
```
> pngquant-bin@3.1.1 postinstall /tmp/git-resource-destination.JfGPDb/node_modules/pngquant-bin
> node lib/install.js

/tmp/git-resource-destination.JfGPDb/node_modules/readable-stream/lib/_stream_transform.js:159
  throw new Error('not implemented');
  ^

Error: not implemented
    at Transform._transform (/tmp/git-resource-destination.JfGPDb/node_modules/readable-stream/lib/_stream_transform.js:159:9)
    at Transform._read (/tmp/git-resource-destination.JfGPDb/node_modules/readable-stream/lib/_stream_transform.js:184:10)
    at Transform._write (/tmp/git-resource-destination.JfGPDb/node_modules/readable-stream/lib/_stream_transform.js:172:12)
    at doWrite (/tmp/git-resource-destination.JfGPDb/node_modules/readable-stream/lib/_stream_writable.js:238:10)
    at writeOrBuffer (/tmp/git-resource-destination.JfGPDb/node_modules/readable-stream/lib/_stream_writable.js:228:5)
    at Transform.Writable.write (/tmp/git-resource-destination.JfGPDb/node_modules/readable-stream/lib/_stream_writable.js:195:11)
    at write (/tmp/git-resource-destination.JfGPDb/node_modules/readable-stream/lib/_stream_readable.js:605:24)
    at flow (/tmp/git-resource-destination.JfGPDb/node_modules/readable-stream/lib/_stream_readable.js:614:7)
    at /tmp/git-resource-destination.JfGPDb/node_modules/readable-stream/lib/_stream_readable.js:582:7
    at nextTickCallbackWith0Args (node.js:436:9)
```

**Comment by shinnn** [comment]
From your other issue reports like https://github.com/imagemin/optipng-bin/issues/82#issuecomment-271782518, you didn't install the npm packages correctly. Remove `node_module` directory, clear cache and run `npm install` again.
