### ISSUE TITLE
Callback() Can Only Be Called Once???? Manjaro Linux

### ISSUE THREAD

**Issue by tytondon1234** [imagemin/pngquant-bin#81]
⚠ EACCES: permission denied, mkdir '/usr/lib/node_modules/pngquant-bin/vendor'
  ⚠ pngquant pre-build test failed
  ℹ compiling from source
  ✔ pngquant pre-build test passed successfully
/usr/lib/node_modules/pngquant-bin/node_modules/onetime/index.js:15
				throw new Error(fnName + ' can only be called once.');
				^

Error: callback() can only be called once.
    at onetime (/usr/lib/node_modules/pngquant-bin/node_modules/onetime/index.js:15:11)
    at /usr/lib/node_modules/pngquant-bin/node_modules/bin-wrapper/node_modules/download/index.js:156:5
    at ConcatStream.<anonymous> (/usr/lib/node_modules/pngquant-bin/node_modules/concat-stream/index.js:37:43)
    at ConcatStream.emit (events.js:185:15)
    at finishMaybe (/usr/lib/node_modules/pngquant-bin/node_modules/readable-stream/lib/_stream_writable.js:630:14)
    at endWritable (/usr/lib/node_modules/pngquant-bin/node_modules/readable-stream/lib/_stream_writable.js:638:3)
    at ConcatStream.Writable.end (/usr/lib/node_modules/pngquant-bin/node_modules/readable-stream/lib/_stream_writable.js:594:41)
    at DuplexWrapper.onend (/usr/lib/node_modules/pngquant-bin/node_modules/readable-stream/lib/_stream_readable.js:577:10)
    at Object.onceWrapper (events.js:272:13)
    at DuplexWrapper.emit (events.js:185:15)
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! pngquant-bin@4.0.0 postinstall: `node lib/install.js`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the pngquant-bin@4.0.0 postinstall script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /root/.npm/_logs/2018-04-25T21_22_14_074Z-debug.log

**Comment by frankshaka** [comment]
Try appending `--unsafe-perm=true --allow-root` to npm install command, e.g.

```bash
npm install -g pngquant-bin --allow-root  --unsafe-perm=true
```

**Comment by tytondon1234** [comment]
It worked. Thanks so much!
