### ISSUE TITLE
Can't install at alpine in Docker container

### ISSUE THREAD

**Issue by vadimshvetsov** [imagemin/pngquant-bin#87]
Thanks for a great work.

I can't build application because of imagemin-pngquant failing.

Here is npm log:
```
13 verbose stack Error: sdelaem-client@0.1.0 build: `NODE_ENV=production webpack --config ./webpack/webpack.prod.js`
13 verbose stack Exit status 2
13 verbose stack     at EventEmitter.<anonymous> (/usr/local/lib/node_modules/npm/node_modules/npm-lifecycle/index.js:285:16)
13 verbose stack     at emitTwo (events.js:126:13)
13 verbose stack     at EventEmitter.emit (events.js:214:7)
13 verbose stack     at ChildProcess.<anonymous> (/usr/local/lib/node_modules/npm/node_modules/npm-lifecycle/lib/spawn.js:55:14)
13 verbose stack     at emitTwo (events.js:126:13)
13 verbose stack     at ChildProcess.emit (events.js:214:7)
13 verbose stack     at maybeClose (internal/child_process.js:925:16)
13 verbose stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:209:5)
14 verbose pkgid sdelaem-client@0.1.0
15 verbose cwd /usr/src/app
16 verbose Linux 4.9.87-linuxkit-aufs
17 verbose argv "/usr/local/bin/node" "/usr/local/bin/npm" "run" "build"
18 verbose node v8.11.3
19 verbose npm  v5.6.0
20 error code ELIFECYCLE
21 error errno 2
```
Here is npm output with error
```
(node:34) UnhandledPromiseRejectionWarning: Error: spawn Unknown system error -8
    at _errnoException (util.js:992:11)
    at ChildProcess.spawn (internal/child_process.js:323:11)
    at Object.exports.spawn (child_process.js:502:9)
    at module.exports (/usr/src/app/node_modules/imagemin-pngquant/node_modules/execa/index.js:204:26)
    at input (/usr/src/app/node_modules/imagemin-pngquant/index.js:50:13)
    at <anonymous>
(node:34) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 2)
(node:34) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
Hash: 742510a5561ff4a04612
Version: webpack 4.8.3
```

I've already checked all the topics in this repo and have all dependencies set.

Here is Dockerfile
```
FROM node:8.10-alpine

RUN set -ex; \
    apk add --no-cache \
        nginx

ENV NODE_ENV production

WORKDIR /usr/src/app

COPY . /usr/src/app

RUN set -ex; \
    apk add --no-cache --virtual .dev-dep \
        lcms2-dev libpng-dev bash \
        git \
        openssh \
        python \
        make \
        g++; \
    npm install; \
    npm run build; \
    mkdir -p /run/nginx; \
    apk del .dev-dep

CMD ["nginx", "-g", "daemon off;"]
```
I would appreciate any help.

**Comment by vadimshvetsov** [comment]
I've figured this out with updating `image-webpack-loader` to 4.3.1 and use loader as following:
```
      {
        test: /\.(jpg|jpeg|gif|png)$/,
        use: [
          {
            loader: 'file-loader',
            options: {
              name: 'assets/images/[name].[ext]',
            },
          },
          {
            loader: 'image-webpack-loader',
            options: {
              disable: true,
            },
          },
        ],
      },

```
instead of
```
      {
        test: /\.(jpg|jpeg|gif|png)$/,
        use: [
          {
            loader: 'file-loader',
            options: {
              name: 'assets/images/[name].[ext]',
            },
          },
          'image-webpack-loader',
        ],
      },

```
That was strange anyway.
